define snmpcollector::device(
		$ensure 						= 'present',
		String $host,
		Integer $port 					= 161,
		Integer $retries 				= 5,
		Integer $timeout				= 20,
		Integer $repeat 				= 0,
		Boolean $active 				= true,
		String $snmp_version 			= '2c',
		String $snmp_community 			= 'public',
		String $snmpv3_sec_level 		= '',
		String $snmpv3_auth_user 		= '',
		String $snmpv3_auth_pass 		= '',
		String $snmpv3_auth_prot 		= '',
		String $snmpv3_priv_pass 		= '',
		String $snmpv3_priv_prot 		= '',
		Boolean $disable_bulk 			= false,
		Integer $max_repetitions 		= 50,
		Integer $frequency 				= 60,
		Integer $update_frequency 		= 60,
		Boolean $concurrent_gather 		= true,
		String $output_database,
		String $log_level 				= 'info',
		String $log_file 				= '',
		Boolean $snmp_debug 			= false,
		String $device_tag_name 		= 'device',
		String $device_tag_value 		= 'id',
		Array $extra_tags 				= [""],
		String $description 			= 'MANAGED BY PUPPET',
		Array $measurement_groups 		= [""],
		Array $measurement_filters		= [""]
)
{
	include snmpcollector::reload

	#TODO: a bunch of validation here.

	snmpcollector_device { $title :
		ensure => $ensure,
		host => $host,
		port => $port,
		retries => $retries,
		timeout => $timeout,
		repeat => $repeat,
		active => $active,
		snmp_version => $snmp_version,
		snmp_community => $snmp_community,
		snmpv3_sec_level => $snmpv3_sec_level,
		snmpv3_auth_user => $snmpv3_auth_user,
		snmpv3_auth_pass => $snmpv3_auth_pass,
		snmpv3_auth_prot => $snmpv3_auth_prot,
		snmpv3_priv_pass => $snmpv3_priv_pass,
		snmpv3_priv_prot => $snmpv3_priv_prot,
		disable_bulk => $disable_bulk,
		max_repetitions => $max_repetitions,
		frequency => $frequency,
		update_frequency => $update_frequency,
		concurrent_gather => $concurrent_gather,
		output_database => $output_database,
		log_level => $log_level,
		log_file => $log_file,
		snmp_debug => $snmp_debug,
		device_tag_name => $device_tag_name,
		device_tag_value => $device_tag_value,
		extra_tags => $extra_tags,
		description => $description,
		measurement_groups => $measurement_groups,
		measurement_filters => $measurement_filters
	} ~> Class['snmpcollector::reload']
}